export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST";
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS";
export const ADMIN_UPDATE_USER_FAIL = "ADMIN_UPDATE_USER_FAIL";
export const ADMIN_UPDATE_USER_RESET = "ADMIN_UPDATE_USER_RESET";

export const ADMIN_LIST_USERS_REQUEST = "ADMIN_LIST_USERS_REQUEST";
export const ADMIN_LIST_USERS_SUCCESS = "ADMIN_LIST_USERS_SUCCESS";
export const ADMIN_LIST_USERS_FAIL = "ADMIN_LIST_USERS_FAIL";
export const ADMIN_LIST_USERS_RESET = "ADMIN_LIST_USERS_RESET";

export const ADMIN_LIST_ALL_USERS_REQUEST = "ADMIN_LIST_ALL_USERS_REQUEST";
export const ADMIN_LIST_ALL_USERS_SUCCESS = "ADMIN_LIST_ALL_USERS_SUCCESS";
export const ADMIN_LIST_ALL_USERS_FAIL = "ADMIN_LIST_ALL_USERS_FAIL";
export const ADMIN_LIST_ALL_USERS_RESET = "ADMIN_LIST_ALL_USERS_RESET";

export const FLAG_USER_COVID_REQUEST = "FLAG_USER_COVID_REQUEST";
export const FLAG_USER_COVID_SUCCESS = "FLAG_USER_COVID_SUCCESS";
export const FLAG_USER_COVID_FAIL = "FLAG_USER_COVID_FAIL";
export const FLAG_USER_COVID_RESET = "FLAG_USER_COVID_RESET";
