export const DOCTOR_LIST_PATIENTS_REQUEST = "DOCTOR_LIST_PATIENTS_REQUEST";
export const DOCTOR_LIST_PATIENTS_SUCCESS = "DOCTOR_LIST_PATIENTS_SUCCESS";
export const DOCTOR_LIST_PATIENTS_FAIL = "DOCTOR_LIST_PATIENTS_FAIL";
export const DOCTOR_LIST_PATIENTS_RESET = "DOCTOR_LIST_PATIENTS_RESET";
