export const DOCTOR_LIST_PATIENTS_REQUEST = "DOCTOR_LIST_PATIENTS_REQUEST";
export const DOCTOR_LIST_PATIENTS_SUCCESS = "DOCTOR_LIST_PATIENTS_SUCCESS";
export const DOCTOR_LIST_PATIENTS_FAIL = "DOCTOR_LIST_PATIENTS_FAIL";
export const DOCTOR_LIST_PATIENTS_RESET = "DOCTOR_LIST_PATIENTS_RESET";

export const DOCTOR_VIEW_REPORT_REQUEST = "DOCTOR_VIEW_REPORT_REQUEST";
export const DOCTOR_VIEW_REPORT_SUCCESS = "DOCTOR_VIEW_REPORT_SUCCESS";
export const DOCTOR_VIEW_REPORT_FAIL = "DOCTOR_VIEW_REPORT_FAIL";
export const DOCTOR_VIEW_REPORT_RESET = "DOCTOR_VIEW_REPORT_RESET";

export const DOCTOR_LIST_APPOINTMENTS_REQUEST =
  "DOCTOR_LIST_APPOINTMENTS_REQUEST";
export const DOCTOR_LIST_APPOINTMENTS_SUCCESS =
  "DOCTOR_LIST_APPOINTMENTS_SUCCESS";
export const DOCTOR_LIST_APPOINTMENTS_FAIL = "DOCTOR_LIST_APPOINTMENTS_FAIL";
export const DOCTOR_LIST_APPOINTMENTS_RESET = "DOCTOR_LIST_APPOINTMENTS_RESET";
