export const DOCTOR_LIST_PATIENTS_REQUEST = "DOCTOR_LIST_PATIENTS_REQUEST";
export const DOCTOR_LIST_PATIENTS_SUCCESS = "DOCTOR_LIST_PATIENTS_SUCCESS";
export const DOCTOR_LIST_PATIENTS_FAIL = "DOCTOR_LIST_PATIENTS_FAIL";
export const DOCTOR_LIST_PATIENTS_RESET = "DOCTOR_LIST_PATIENTS_RESET";

export const DOCTOR_SCHEDULE_APPOINTMENT_REQUEST =
  "DOCTOR_SCHEDULE_APPOINTMENT_REQUEST";
export const DOCTOR_SCHEDULE_APPOINTMENT_SUCCESS =
  "DOCTOR_SCHEDULE_APPOINTMENT_SUCCESS";
export const DOCTOR_SCHEDULE_APPOINTMENT_FAIL =
  "DOCTOR_SCHEDULE_APPOINTMENT_FAIL";
export const DOCTOR_SCHEDULE_APPOINTMENT_RESET =
  "DOCTOR_SCHEDULE_APPOINTMENT_RESET";

export const DOCTOR_LIST_APPOINTMENTS_REQUEST =
  "DOCTOR_LIST_APPOINTMENTS_REQUEST";
export const DOCTOR_LIST_APPOINTMENTS_SUCCESS =
  "DOCTOR_LIST_APPOINTMENTS_SUCCESS";
export const DOCTOR_LIST_APPOINTMENTS_FAIL = "DOCTOR_LIST_APPOINTMENTS_FAIL";
export const DOCTOR_LIST_APPOINTMENTS_RESET = "DOCTOR_LIST_APPOINTMENTS_RESET";
