export const PATIENT_REPORT_CONTACTED_REQUEST =
  "PATIENT_REPORT_CONTACTED_REQUEST";
export const PATIENT_REPORT_CONTACTED_SUCCESS =
  "PATIENT_REPORT_CONTACTED_SUCCESS";
export const PATIENT_REPORT_CONTACTED_FAIL = "PATIENT_REPORT_CONTACTED_FAIL";
export const PATIENT_REPORT_CONTACTED_RESET = "PATIENT_REPORT_CONTACTED_RESET";
