POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name" : "FlaggedUser",
    "lname": "FlaggedUser",
    "email":"Flagged@User",
    "password":"pass",
    "cpassword": "pass",
    "roles": "user"

}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name" : "User",
    "lname": "buser",
    "email":"user@user",
    "password":"pass",
    "cpassword": "pass",
    "roles": ""

}
###
PUT http://localhost:8080/api/auth/resetPassword
Content-Type: application/json

{
    "email" : "soen390testing@gmail.com",
    "currentPassword" : "123",
    "newPassword":"pass"
    
}

###
GET http://localhost:8080/api/test/all

###
GET http://localhost:8080/api/test/user
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjVkYWMxY2IwZmZjM2U1NzM3ZDc3YiIsImlhdCI6MTY0MzUwMjc2NiwiZXhwIjoxNjQzNTg5MTY2fQ.3FEaFI5poQw0_18OuOVbEPPHCK68v2bV-XowYYFKbPo


###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "email":"user@user",
    "password":"pass"
}

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "email":"zaatar@yopmail.com",
    "password":"123"
}

###
GET http://localhost:8080/api/verify/admin
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjhhOGY2OGU2OWE5ZTFkYTFiMmUyOSIsImlhdCI6MTY0Mzc2NDk1MiwiZXhwIjoxNjQzODUxMzUyfQ._OWiBjMSZlSYnYRREG6_CnP663v0NHoOEwN99eB4bYw

###
PUT http://localhost:8080/api/verify/admin
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjhhOGY2OGU2OWE5ZTFkYTFiMmUyOSIsImlhdCI6MTY0MzY4NjQ4OCwiZXhwIjoxNjQzNzcyODg4fQ.3K9FWbSzxwWd2RbC-CTy5202vr74QPNc6Pf0Gd5YfMk

{
    "id": "61f8a9578e69a9e1da1b2e38"
}
###
PUT http://localhost:8080/api/verify/confirmDetails
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjg4MjU5YWEwNzE5ODI1Y2EwYWExNyIsImlhdCI6MTY0MzY3NjM1OSwiZXhwIjoxNjQzNzYyNzU5fQ.NdNHUXsvG-k8OGnsopkacN9Ve3L72EQG-NFjKDljAoo

{
    
}

###

POST http://localhost:8080/api/view/assign
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NzEzODYzNywiZXhwIjoxNjQ3MjI1MDM3fQ.ztdKipSiEsVMD946zpyGrOf3NY2QvveCyfkqssT5pxM

{
    "doctorId": "6206d9a5c48f73131c34f3ef",
    "userId": "62129bdba14bf47689f1f95f"
}

###
GET http://localhost:8080/api/view/62129bdba14bf47689f1f95f
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOTAzMjY0ZWE3MTg1OWMxZDk3NCIsImlhdCI6MTY0NTQxNzIxNiwiZXhwIjoxNjQ1NTAzNjE2fQ.Zbpbq3WAKJDU8fbgpcEXsgK23s0o41FW-L0jbRCOMtI

{
    
}

###
GET http://localhost:8080/api/view
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NzEzODYzNywiZXhwIjoxNjQ3MjI1MDM3fQ.ztdKipSiEsVMD946zpyGrOf3NY2QvveCyfkqssT5pxM

{

}

###
GET http://localhost:8080/api/view/620eca00f1eb719f8011f97d
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NzEzODYzNywiZXhwIjoxNjQ3MjI1MDM3fQ.ztdKipSiEsVMD946zpyGrOf3NY2QvveCyfkqssT5pxM

{
    
}

###
PUT http://localhost:8080/api/view/requestReport
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NTM4OTcyNCwiZXhwIjoxNjQ1NDc2MTI0fQ.CJKBziUEViXcReMptWiEBWH3aSh_KS_eiBWQnro08n8

{
   "userId": "620eca00f1eb719f8011f97d"  
}

###
PUT http://localhost:8080/api/view/fillReport
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0Njk3MjM4OCwiZXhwIjoxNjQ3MDU4Nzg4fQ.LyD58FN8YPYiAd6Sz5c80pjyqtZQE-AbK7To9ikaDaM

{
    "hasCovid": true,
    "hasTravelled": false,
    "hasAutoImmuneDisease": false,
    "isPregnant": false,
    "hadAllergicReaction": false
}

###
GET http://localhost:8080/api/view/fillReport/getCustom
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0Njk3MjM4OCwiZXhwIjoxNjQ3MDU4Nzg4fQ.LyD58FN8YPYiAd6Sz5c80pjyqtZQE-AbK7To9ikaDaM

{

}

###
GET http://localhost:8080/api/view/620eca00f1eb719f8011f97d/report
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NTQwMDI0MywiZXhwIjoxNjQ1NDg2NjQzfQ.mkX1LQtbXy01-xtZoTiEPsYrLrSAz1nYGgcCzDLozWg

{

}

###
POST http://localhost:8080/api/contactedPeople
Content-Type:  application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTMwY2Q5MTQxZGYyODc2N2NiZDNmOSIsImlhdCI6MTY0OTAwNDI2NywiZXhwIjoxNjQ5MDkwNjY3fQ.T8g-kx7pl8w-WF6k3QxuZDIiupP5wtxbFV961w-vBjw

{
    "name":"mareed6",
    "lname":"mareed",
    "email":"mareed5@yopmail.com"
}

###
GET http://localhost:8080/api/contactedPeopleList
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMTMwY2Q5MTQxZGYyODc2N2NiZDNmOSIsImlhdCI6MTY0OTAwNDI2NywiZXhwIjoxNjQ5MDkwNjY3fQ.T8g-kx7pl8w-WF6k3QxuZDIiupP5wtxbFV961w-vBjw

{
    
}

###
GET http://localhost:8080/api/view/user/myreport
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0Njg3MzE1NiwiZXhwIjoxNjQ2OTU5NTU2fQ.GbOTBlbe-psbauCJgxhxQ69OLzbfl4aNZAL9L7xLo_c

{
 
}

###
POST http://localhost:8080/api/appointmentBooking
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NzIyNDk2NywiZXhwIjoxNjQ3MzExMzY3fQ.2Z-ulNywgFDe8IHpsa2b-C3DdBp0Op8hjVEOZ5nQCxU

{
    "userId":"620eca00f1eb719f8011f97d",
    "appointmentDate":"2022-12-30T16:00:00Z",
    "description":"kfaklmflka"
}

###
GET  http://localhost:8080/api/appointmentsWithPatients
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NzIyNDk2NywiZXhwIjoxNjQ3MzExMzY3fQ.2Z-ulNywgFDe8IHpsa2b-C3DdBp0Op8hjVEOZ5nQCxU

{
    
}

###

GET http://localhost:8080/api/view/report/all/mypatients
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0Njk2Mjc0MiwiZXhwIjoxNjQ3MDQ5MTQyfQ.SY7WqteV-IcVeQniSxpEq9aIGA_lec7E1S_ROzUVIDk

{


}

###
PUT http://localhost:8080/api/view/620eca00f1eb719f8011f97d/report/viewed/6212ac8293c2fd5209e61c6c
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0Njk2Mjc0MiwiZXhwIjoxNjQ3MDQ5MTQyfQ.SY7WqteV-IcVeQniSxpEq9aIGA_lec7E1S_ROzUVIDk

{
    
}

###
GET http://localhost:8080/api/view/user/myreport/622b834e3ab51af6ba7cc19d
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0NzE0MDE4OSwiZXhwIjoxNjQ3MjI2NTg5fQ.3X05fdakeKDlfCK2zpFAZTvwqshutT6lktH-7hHUvRo

{


}

###
PUT http://localhost:8080/api/view/user/myreport/622b834e3ab51af6ba7cc19d
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0NzE0MDE4OSwiZXhwIjoxNjQ3MjI2NTg5fQ.3X05fdakeKDlfCK2zpFAZTvwqshutT6lktH-7hHUvRo

{
    "hasCovid": true,
    "hasTravelled": false,
    "hasAutoImmuneDisease": false,
    "isPregnant": false,
    "hadAllergicReaction": false,
    "Temperature": 35,
    "Weight": 72,
    "Height": 190,
    "customAns": "A little bit"

}

###
GET http://localhost:8080/api/message/myDoctor
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0ODk5ODQzMCwiZXhwIjoxNjQ5MDg0ODMwfQ.PAl_dF5zucs21AxFh7S7wPMN69RuXhpsh3wiV2OC-Lc

{

}

###
GET http://localhost:8080/api/message/myPatients
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0ODc2MjcxNywiZXhwIjoxNjQ4ODQ5MTE3fQ.vtej4Pfo9xwaAQcbTEaOus36PhShlvnd8i5U4n62szQ

{

}

###
POST http://localhost:8080/api/message/recipient/620bdf6a54190d942f5fcf02
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0ODc2NTM5NCwiZXhwIjoxNjQ4ODUxNzk0fQ.jALvAfG39OzF3zEc-P_l_-g3ihxhiSN3S68S3TziQaE

{
    "message": "Have you done x",
    "emergency": true
}

###
GET http://localhost:8080/api/message/recipient/6206d9a5c48f73131c34f3ef
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0ODc2NDg0OCwiZXhwIjoxNjQ4ODUxMjQ4fQ.IfzAbV9K2BOhMskUJ4XsRpLAN8KfB25XVIqlLjjAyvs

{

}

###
GET http://localhost:8080/api/message/emergency/recipient/6206d9a5c48f73131c34f3ef
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0ODc2NDg0OCwiZXhwIjoxNjQ4ODUxMjQ4fQ.IfzAbV9K2BOhMskUJ4XsRpLAN8KfB25XVIqlLjjAyvs

{

}

###
PUT http://localhost:8080/api/message/seen/emergency/recipient/62463336bbf1390ded1f0a9f
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGJkZjZhNTQxOTBkOTQyZjVmY2YwMiIsImlhdCI6MTY0ODc2NDg0OCwiZXhwIjoxNjQ4ODUxMjQ4fQ.IfzAbV9K2BOhMskUJ4XsRpLAN8KfB25XVIqlLjjAyvs

{

}