POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name" : "health",
    "lname": "official",
    "email":"health_official@gmail.com",
    "password":"pass",
    "cpassword": "pass",
    "roles": "health_official"

}

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name" : "User",
    "lname": "buser",
    "email":"user@user",
    "password":"pass",
    "cpassword": "pass",
    "roles": ""

}
###
PUT http://localhost:8080/api/auth/resetPassword
Content-Type: application/json

{
    "email" : "soen390testing@gmail.com",
    "currentPassword" : "123",
    "newPassword":"pass"
    
}

###
GET http://localhost:8080/api/test/all

###
GET http://localhost:8080/api/test/user
Content-Type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjVkYWMxY2IwZmZjM2U1NzM3ZDc3YiIsImlhdCI6MTY0MzUwMjc2NiwiZXhwIjoxNjQzNTg5MTY2fQ.3FEaFI5poQw0_18OuOVbEPPHCK68v2bV-XowYYFKbPo


###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "email":"doctor@doctor.com",
    "password":"doctor"
}

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
    "email":"patient@patient.com",
    "password":"patient"
}

###
GET http://localhost:8080/api/verify/admin
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjhhOGY2OGU2OWE5ZTFkYTFiMmUyOSIsImlhdCI6MTY0Mzc2NDk1MiwiZXhwIjoxNjQzODUxMzUyfQ._OWiBjMSZlSYnYRREG6_CnP663v0NHoOEwN99eB4bYw

###
PUT http://localhost:8080/api/verify/admin
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjhhOGY2OGU2OWE5ZTFkYTFiMmUyOSIsImlhdCI6MTY0MzY4NjQ4OCwiZXhwIjoxNjQzNzcyODg4fQ.3K9FWbSzxwWd2RbC-CTy5202vr74QPNc6Pf0Gd5YfMk

{
    "id": "61f8a9578e69a9e1da1b2e38"
}
###
PUT http://localhost:8080/api/verify/confirmDetails
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjg4MjU5YWEwNzE5ODI1Y2EwYWExNyIsImlhdCI6MTY0MzY3NjM1OSwiZXhwIjoxNjQzNzYyNzU5fQ.NdNHUXsvG-k8OGnsopkacN9Ve3L72EQG-NFjKDljAoo

{
    
}

###

POST http://localhost:8080/api/view/assign
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOTAzMjY0ZWE3MTg1OWMxZDk3NCIsImlhdCI6MTY0NTM3NDcwNywiZXhwIjoxNjQ1NDYxMTA3fQ.j8fgj59lYo56PJFlg3bBGrIiMedsa7pzOtR5Rs51w5c

{
    "doctorId": "6206d9a5c48f73131c34f3ef",
    "userId": "620eca00f1eb719f8011f97d"

}

###
GET http://localhost:8080/api/view/61f8a8fd8e69a9e1da1b2e2e
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOTAzMjY0ZWE3MTg1OWMxZDk3NCIsImlhdCI6MTY0NTM3NDcwNywiZXhwIjoxNjQ1NDYxMTA3fQ.j8fgj59lYo56PJFlg3bBGrIiMedsa7pzOtR5Rs51w5c

{
    
}

###
GET http://localhost:8080/api/view
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOTAzMjY0ZWE3MTg1OWMxZDk3NCIsImlhdCI6MTY0NTM3NDcwNywiZXhwIjoxNjQ1NDYxMTA3fQ.j8fgj59lYo56PJFlg3bBGrIiMedsa7pzOtR5Rs51w5c

{
    
}

###
PUT http://localhost:8080/api/view/requestReport
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMDZkOWE1YzQ4ZjczMTMxYzM0ZjNlZiIsImlhdCI6MTY0NTM4OTcyNCwiZXhwIjoxNjQ1NDc2MTI0fQ.CJKBziUEViXcReMptWiEBWH3aSh_KS_eiBWQnro08n8

{
   "userId": "620eca00f1eb719f8011f97d"  
}

###
PUT http://localhost:8080/api/view/fillReport
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMGVjYTAwZjFlYjcxOWY4MDExZjk3ZCIsImlhdCI6MTY0NTM4OTg2OCwiZXhwIjoxNjQ1NDc2MjY4fQ.-mUsQB5k6t-BodI2X9m1-mHlEIJ_7Q5YUE4G3_EkTIk

{
    "hasCovid": false,
    "hasTravelled": false,
    "hasAutoImmuneDisease": false,
    "isPregnant": false,
    "hadAllergicReaction": false
}